# Generated by Django 4.1.6 on 2023-02-10 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('API', '0003_alter_contributor_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('tag', models.CharField(choices=[('B', 'Bug'), ('A', 'Amelioration'), ('T', 'Tache')], max_length=20)),
                ('priority', models.CharField(choices=[('F', 'Faible'), ('M', 'Moyenne'), ('E', 'Elevee')], max_length=20)),
                ('status', models.CharField(choices=[('TODO', 'A Faire'), ('IN_PROGRESS', 'En Cours'), ('DONE', 'Termine')], max_length=20)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('assignee_user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignee', to=settings.AUTH_USER_MODEL)),
                ('author_user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.project')),
            ],
        ),
    ]
